version: "3"
services:
    webapp:
        image: henfo/endabgabe
        build: ./
        command: npm start
        ports:
            - "3000:3000"
        depends_on:
            - mongoservice
    mongoservice:
        image: mongo 
        ports:
            - "27017:27017"
    mongoadmin:
        image: mrvautin/adminmongo
        ports:
            - "1234:1234"